//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNAY_New1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNAYallotment
    {
        public int SNO { get; set; }
        public string FormNo { get; set; }
        public string RegNum { get; set; }
        public string ApplicantName { get; set; }
        public string Sex { get; set; }
        public string S_W_D_of { get; set; }
        public string ApplicantAddress { get; set; }
        public string AllotedPlotNo { get; set; }
    }
}
