//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNAY_New1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNAY_Application
    {
        public int ApplicationNumber { get; set; }
        public string ApplicantName { get; set; }
        public string FatherName { get; set; }
        public string Nationality { get; set; }
        public System.DateTime DOB { get; set; }
        public bool IsNRI { get; set; }
        public string PanNo { get; set; }
        public string Occupation { get; set; }
        public string Department { get; set; }
        public int AnnualIncome { get; set; }
        public string EmailId { get; set; }
        public string ContactNumber { get; set; }
        public string CommunicationAddress { get; set; }
        public string CommunicationState { get; set; }
        public string CommunicationPIN { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentState { get; set; }
        public string PermanentPIN { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeState { get; set; }
        public string OfficePIN { get; set; }
        public string CoApplicantApplicantName { get; set; }
        public string CoApplicantFatherName { get; set; }
        public string CoApplicantNationality { get; set; }
        public Nullable<System.DateTime> CoApplicantDOB { get; set; }
        public Nullable<bool> CoApplicantIsNRI { get; set; }
        public string CoApplicantPanNo { get; set; }
        public string CoApplicantOccupation { get; set; }
        public string CoApplicantDepartment { get; set; }
        public Nullable<int> CoApplicantAnnualIncome { get; set; }
        public string CoApplicantEmailId { get; set; }
        public string CoApplicantContactNumber { get; set; }
        public string CoApplicantCommunicationAddress { get; set; }
        public string CoApplicantCommunicationState { get; set; }
        public string CoApplicantCommunicationPIN { get; set; }
        public string CoApplicantPermanentAddress { get; set; }
        public string CoApplicantPermanentState { get; set; }
        public string CoApplicantPermanentPIN { get; set; }
        public string CoApplicantOfficeAddress { get; set; }
        public string CoApplicantOfficeState { get; set; }
        public string CoApplicantOfficePIN { get; set; }
        public string AppliedProject { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> CarpetAreaInFoot { get; set; }
        public string PaymentPlan { get; set; }
        public Nullable<int> AmountPayable { get; set; }
        public string ApplicationPaymentID { get; set; }
        public string PaymentReceipt { get; set; }
        public string RefundAccNo { get; set; }
        public string RefundBankName { get; set; }
        public string RefundBankIFSC { get; set; }
        public Nullable<bool> IsFirstProperty { get; set; }
        public Nullable<int> LoanAmountRequired { get; set; }
        public Nullable<int> MonthlyGrossIncome { get; set; }
        public Nullable<int> MonthlyNetIncome { get; set; }
        public Nullable<bool> AnyPreviousLoan { get; set; }
        public Nullable<int> PreviousLoanEMI { get; set; }
        public Nullable<int> PreviousLoanBalance { get; set; }
        public string ApplicationIPAddress { get; set; }
        public string ClubbedIncomeFamilyMemberName { get; set; }
        public Nullable<int> ClubbedmemberMonthlyNetIncome { get; set; }
        public Nullable<bool> ClubbedmemberAnyPreviousLoan { get; set; }
        public Nullable<int> ClubbedmemberPreviousLoanEMI { get; set; }
        public Nullable<int> ClubbedmemberPreviousLoanBalance { get; set; }
        public string EmployeeIDCopy { get; set; }
        public string PanCardCopy { get; set; }
        public string AddressProofCopy { get; set; }
        public string ApplicantPhoto { get; set; }
        public string CoApplicantPhoto { get; set; }
        public Nullable<System.DateTime> DateOfSubmit { get; set; }
        public Nullable<bool> IsReceptVerified { get; set; }
        public string ReceptVerifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<decimal> bookingamount { get; set; }
        public Nullable<bool> bookingamountpaid { get; set; }
    }
}
